from turtle import*
clr =("black","violet","pink","blue","green","yellow","orange","red","navy blue","light green")
pensize(3)
for n in clr:
    color("black",n)
    begin_fill()
    circle(10)
    circle(20)
    circle(30)
    circle(40)
    circle(50)
    circle(60)
    circle(70)
    circle(80)
    circle(90)
    circle(100)
    circle(110)
    circle(120)
    circle(130)
    circle(140)
    circle(150)
    end_fill()
    rt(45)
